
/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "proxy.h"
#include "protocol.h"
#include <pthread.h>

extern int nodetype;
pthread_t request_thread;

int main (int argc, char *argv[])
{
    nodetype = EXIT;
    protocol_init();
    pthread_create(&request_thread, NULL, start_request, NULL);
    run();
}
