/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "proxy.h"
#include <string.h>

typedef int bool;

#define true 1
#define false 0

int total_num;
static bool lock;
static char pid_list[1024];

void proxy_init() {
    lock = false;
    printf("请输入停车场停车位总数：");
    scanf("%d", &total_num);
    printf("一共有%d个停车位\n", total_num);
    pid_list[0] = '\0';
}

char **
get_pid_list_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
    if (lock) {
        result = "#";
    } else {
        lock = true;
        result = pid_list;
    }

	return &result;
}

int *
comfirm_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
    char tmp_pid[8];
    if (strlen(pid_list) == 0)
        sprintf(tmp_pid, "%d", *argp);
    else
        sprintf(tmp_pid, " %d", *argp);
    strcat(pid_list, tmp_pid);
    lock = false;
    result = total_num;

    return &result;
}
