/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROXY_H_RPCGEN
#define _PROXY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PROXY 0x12345678
#define PROXY_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_PID_LIST 1
extern  char ** get_pid_list_1(int *, CLIENT *);
extern  char ** get_pid_list_1_svc(int *, struct svc_req *);
#define COMFIRM 2
extern  int * comfirm_1(int *, CLIENT *);
extern  int * comfirm_1_svc(int *, struct svc_req *);
extern int proxy_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_PID_LIST 1
extern  char ** get_pid_list_1();
extern  char ** get_pid_list_1_svc();
#define COMFIRM 2
extern  int * comfirm_1();
extern  int * comfirm_1_svc();
extern int proxy_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROXY_H_RPCGEN */
